version: '3.5'

services:
  proxy:
    image: nginx:latest
    container_name: proxy_jalet19
    depends_on: 
      - backend
    volumes: 
      - ./etc/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./etc/nginx/ssl/:/etc/nginx/ssl/
      - ./html/:/etc/nginx/html/
    networks:
      - frontend
    ports: 
      - "443:443"

  backend:
    build: ./etc/flask/
    image: flask:0.0.1
    container_name: backend_jalet19
    depends_on: 
      - database
    ports: 
      - "5000:5000"
    networks:
      frontend:
      backend:

  database:
    image: mysql:latest
    container_name: database_jalet19
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./etc/mysql/backend/:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    networks:
      - backend

networks:
  frontend:
  backend:
